version: '3'
services:
  backend-api-service:
    build: './backend'
    ports:
      - "4000:4000"

  frontend-service:
    build: './frontend'
    ports:
      - "3000:3000"

  chatbot-service:
    build: './chatbot'
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-api-service
      - frontend-service
      - chatbot-service